# Generated by Django 5.1.5 on 2025-01-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='наименование')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='номер стола')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('в ожидании', 'в ожидании'), ('готово', 'готово'), ('оплачено', 'оплачено')], default='в ожидании', max_length=255, verbose_name='статус')),
                ('items', models.ManyToManyField(blank=True, to='core.item', verbose_name='позиции')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table', verbose_name='стол')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('id',),
            },
        ),
    ]
