# Generated by Django 5.1.5 on 2025-01-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='наименование')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
                'ordering': ('id',),
            },
        ),
    ]
