# Generated by Django 5.1.5 on 2025-01-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'в ожидании'), ('done', 'выполнен'), ('cancel', 'отменен')], default='pending', max_length=255, verbose_name='статус')),
                ('items', models.ManyToManyField(blank=True, to='core.item', verbose_name='позиции')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table', verbose_name='стол')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('id',),
            },
        ),
    ]
