# Generated by Django 5.1.5 on 2025-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='номер стола')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
                'ordering': ('id',),
            },
        ),
    ]
